### ISSUE TITLE
The issue when accessing API (/service-info)

### ISSUE THREAD

**Issue by KaiJiaBrother** [sapporo-wes/sapporo-service#35] opened 2023-11-29 10:06 UTC
I deployed `sapporo-service` with Docker Desktop for Windows, see below:

![image](https://github.com/sapporo-wes/sapporo-service/assets/26372175/dc11a526-fb1a-4119-b1fc-616096aea2df)

The status of `sapporo-service` is running and everything looks fine.

As I referenced [SwaggerUI - sapporo-wes - GetExecutableWorkflows](https://app.swaggerhub.com/apis/suecharo/sapporo-wes/sapporo-wes-1.0.1-oas3#/default/GetExecutableWorkflows), I tried different APIs.

However, `http://127.0.0.1:1122/service-info` cannot be accessed, `http://127.0.0.1:1122/executable-workflows` can be accessible, look below:

![image](https://github.com/sapporo-wes/sapporo-service/assets/26372175/bfa00056-64e8-4582-9f29-fc7285048fdf)

![image](https://github.com/sapporo-wes/sapporo-service/assets/26372175/5777d651-e4ca-4050-9ac2-ed3ddc35bb45)

So how to solve this issue?

**Comment by suecharo** [comment] 2023-11-30 05:13
@KaiJiaBrother 
Hello, thank you for reaching out.
Regarding Docker Desktop for Windows, it is the least debugged environment in our experience, as we primarily use a Linux environment.
I believe you are currently using the official Docker image created based on https://github.com/sapporo-wes/sapporo-service/blob/main/Dockerfile.

If possible, could you please update the Docker launch command for debugging purposes and restart it? The commands are as follows:

```
$ docker run -d --rm -p 1122:1122 --name spr-dev ghcr.io/sapporo-wes/sapporo-service:1.5.1 sapporo --debug
$ curl localhost:1122/service-info
$ docker logs spr-dev
```

I would appreciate it if you could paste the results here.

**Comment by KaiJiaBrother** [comment] 2023-12-19 08:50
@suecharo Hi suecharo, is there any updates? thanks a lot!

**Comment by inutano** [comment] 2023-12-19 08:55
Hi @KaiJiaBrother ! I guess the issue is related to the permission to access your file system from inside the container, I can't reproduce the issue because I usually don't use Windows machines though. I recommend using our docker image as you already tried, but do you see any issues with using that?

**Comment by KaiJiaBrother** [comment] 2023-12-19 09:46
Hi @inutano, thanks for your quick reply! I've tried using the docker image in the command line mode and it works fine. I guess `docker-compose.yml` does not work properly with Docker Desktop for Windows. Any way, I could use docker image in the command line mode.

**Comment by inutano** [comment] 2023-12-20 08:12
Maybe the volume mount settings in https://github.com/sapporo-wes/sapporo-service/blob/1a3fdf88d4f2d0e2d793ebf7a41257bef9877b7f/docker-compose.yml#L8-L10 is not working properly on Docker for Windows.  The first line is for your working directory, the second is for docker siblings, and the last one is for tmp to be used in workflow engines. It's possible in Windows (or in the setting of your Docker Windows) you cannot mount them at least with these paths. You can edit them to see if the other settings can work if you want to try - thanks a lot for trying anyway! 

I'm closing this but feel free to open a new issue when needed.

**Closed by inutano** 2023-12-20 08:12 UTC
